###create author
post http://localhost:4000/admin-api/user
Content-Type: application/json


{
    "userType":"author",
    "username":"vikas",
    "password":"vikas",
    "email":"vikas@mail.com"
}


###login author
post http://localhost:4000/admin-api/login
Content-Type: application/json


{
    "userType":"author",
    "username":"vikas",
    "password":"vikas"   
}

