
###user creation
post http://localhost:4000/user-api/user
Content-Type: application/json

{
    "userType":"user",
    "username":"ravi",
    "password":"ravi",
    "email":"ravi@mail.com"
}

#### user login
post http://localhost:4000/user-api/login
Content-Type: application/json

{
    "userType":"user",
    "username":"ravi",
    "password":"ravi"
   
}


